/**
 * One-time enrichment migration — runs at server startup.
 * Upserts all watches with complete specs + adds new watches to match
 * the images in client/public/watches-collection/.
 *
 * Safe to run multiple times (keyed on referenceNumber).
 */
import { eq } from "drizzle-orm";
import { getDb } from "../db";
import * as schema from "../../drizzle/schema";

async function upsertWatch(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, w: schema.InsertWatch) {
  const existing = await db
    .select({ id: schema.watches.id })
    .from(schema.watches)
    .where(eq(schema.watches.referenceNumber, w.referenceNumber!))
    .limit(1);

  if (existing.length) {
    await db.update(schema.watches).set(w).where(eq(schema.watches.id, existing[0].id));
  } else {
    await db.insert(schema.watches).values(w);
  }
}

async function brandId(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, slug: string): Promise<number> {
  const rows = await db
    .select({ id: schema.brands.id })
    .from(schema.brands)
    .where(eq(schema.brands.slug, slug))
    .limit(1);
  if (!rows.length) throw new Error(`Brand not found: ${slug}`);
  return rows[0].id;
}

export async function enrichWatchCollection() {
  const db = await getDb();
  if (!db) {
    console.warn("[Migration] enrichWatchCollection: DB not available, skipping.");
    return;
  }

  // Guard — skip if the RM 68-01 Cyril Kongo is already present
  const guard = await db
    .select({ id: schema.watches.id })
    .from(schema.watches)
    .where(eq(schema.watches.referenceNumber, "RM 68-01"))
    .limit(1);
  if (guard.length) {
    console.log("[Migration] enrichWatchCollection: already applied, skipping.");
    return;
  }

  console.log("[Migration] enrichWatchCollection: starting…");

  const patek = await brandId(db, "patek-philippe");
  const rm    = await brandId(db, "richard-mille");
  const ap    = await brandId(db, "audemars-piguet");
  const rolex = await brandId(db, "rolex");
  const fpj   = await brandId(db, "fp-journe");
  const moser = await brandId(db, "h-moser-cie");
  const tudor = await brandId(db, "tudor");
  const breit = await brandId(db, "breitling");

  const watches: schema.InsertWatch[] = [
    // ── F.P. JOURNE ───────────────────────────────────────────────────────
    {
      brandId: fpj,
      referenceNumber: "Chronometre-Resonance-Japan-20",
      nameEn: "F.P. Journe Chronomètre à Résonance Japan 20th Anniversary",
      nameAr: "إف بي جورن كرونومتر ريزونانس - الذكرى الـ 20 لليابان",
      slug: "fp-journe-chronom-tre-r-sonance",
      descriptionEn: "Limited to 300 pieces celebrating 20 years of F.P. Journe in Japan. The 40 mm titanium case houses an 18K red-gold movement dial and the legendary resonance complication — two independent escapements that oscillate in harmonic sympathy, dramatically improving long-term accuracy.",
      descriptionAr: "محدود بـ 300 قطعة احتفالاً بـ 20 عامًا من إف بي جورن في اليابان. غلاف تيتانيوم 40 مم مع ميناء ذهب أحمر وتعقيد الرنين الأسطوري.",
      storyEn: "François-Paul Journe's resonance complication is the most difficult in horology: two separate balance wheels synchronise through the mainplate and thereafter run together with extraordinary precision. This anniversary edition wraps that achievement in aerospace-grade titanium.",
      storyAr: "تعقيد الرنين عند جورن هو الأصعب في الساعاتية: عجلتا توازن مستقلتان تتزامنان لتحقيق دقة استثنائية.",
      material: "Titanium / 18K Red Gold movement dial",
      dialColor: "18K Red Gold",
      caseSize: "40mm",
      movement: "Caliber 1499.3 — Manual-winding, Resonance",
      complications: "Resonance, Hours, Minutes, Power Reserve",
      powerReserve: "56 hours",
      waterResistance: "30m",
      limitedEdition: true,
      productionQuantity: 300,
      yearReleased: 2019,
      retailPrice: 101000,
      marketValue: 340000,
      rarity: "Extremely Rare",
      mainImageUrl: "/watches-collection/fp-journe-resonance-1681913779906_800x.webp",
      isFeatured: true,
      displayOrder: 1,
      isActive: true,
    },

    // ── PATEK PHILIPPE ────────────────────────────────────────────────────
    {
      brandId: patek,
      referenceNumber: "5470P-001",
      nameEn: "Patek Philippe 5470P-001 Only Watch Chronograph",
      nameAr: "باتيك فيليب 5470P-001 كرونوغراف أونلي ووتش",
      slug: "patek-philippe-5470p",
      descriptionEn: "A one-of-a-kind 41 mm platinum split-seconds chronograph with perpetual calendar and moon phase, created exclusively for Only Watch 2019. It sold for CHF 6.2 million — among the highest ever achieved for a contemporary Patek Philippe.",
      descriptionAr: "قطعة فريدة من نوعها، كرونوغراف بلاتيني 41 مم مع تقويم دائم وطور القمر، أنشئ حصريًا لمزاد Only Watch 2019. بيع بـ 6.2 مليون فرنك سويسري.",
      storyEn: "Ref. 5470P was unveiled at Only Watch 2019 bearing an entirely unique black ébauche. The auction result — more than ten times the retail estimate — confirmed it as one of the most collectible watches of the 21st century.",
      storyAr: "كُشف عن المرجع 5470P في مزاد Only Watch 2019 بمحرك أسود فريد. حقق سعر المزاد أكثر من عشرة أضعاف التقدير الأولي.",
      material: "Platinum 950",
      dialColor: "Black ébauche (unique)",
      caseSize: "41mm",
      movement: "Caliber CHR 29-535 PS Q — Manual-winding, Split-Seconds Chronograph + Perpetual Calendar",
      complications: "Split-Seconds Chronograph, Perpetual Calendar, Moon Phase, Date, Day, Month, Leap Year",
      powerReserve: "65 hours",
      waterResistance: "30m",
      limitedEdition: true,
      productionQuantity: 1,
      yearReleased: 2019,
      retailPrice: 500000,
      marketValue: 6200000,
      rarity: "Unique — 1 of 1",
      mainImageUrl: "/watches-collection/patek-1674210655318_800x.webp",
      isFeatured: true,
      displayOrder: 2,
      isActive: true,
    },
    {
      brandId: patek,
      referenceNumber: "5326G-001",
      nameEn: "Patek Philippe Calatrava 5326G Travel Time",
      nameAr: "باتيك فيليب كالاتراڤا 5326G تراڤل تايم",
      slug: "patek-philippe-calatrava-5326g-travel-time",
      descriptionEn: "A 38.5 mm white-gold Calatrava housing the Caliber 324 S C FUS. The dual time-zone display with AM/PM indicator is operated by elegant pushers at 8 and 10 o'clock, preserving the dial's pure elegance.",
      descriptionAr: "كالاتراڤا ذهب أبيض 38.5 مم مع كاليبر 324 S C FUS. منطقتان زمنيتان مع مؤشر ص/م.",
      storyEn: "Introduced at Watches & Wonders 2020, the 5326G-001 revives the travel-time complication within a classically proportioned Calatrava, equally at home in a board room or on a transatlantic flight.",
      storyAr: "قُدّمت عام 2020، تُحيي 5326G تعقيد التوقيت المزدوج في هيكل كالاتراڤا الكلاسيكي.",
      material: "18K White Gold",
      dialColor: "Silver Opaline",
      caseSize: "38.5mm",
      movement: "Caliber 324 S C FUS — Automatic",
      complications: "Dual Time Zone, AM/PM Indicator, Date, Sweep Seconds",
      powerReserve: "45 hours",
      waterResistance: "30m",
      yearReleased: 2020,
      retailPrice: 55000,
      marketValue: 70000,
      rarity: "Very Rare",
      mainImageUrl: "/watches-collection/patek-calatrava-5326g-1681913791211_800x.webp",
      isFeatured: true,
      displayOrder: 3,
      isActive: true,
    },
    {
      brandId: patek,
      referenceNumber: "6007A-001",
      nameEn: "Patek Philippe Calatrava 6007A",
      nameAr: "باتيك فيليب كالاتراڤا 6007A",
      slug: "patek-philippe-calatrava-6007a",
      descriptionEn: "A 42 mm stainless-steel Calatrava with anthracite dial — a rare combination for Patek Philippe, available exclusively through boutiques.",
      descriptionAr: "كالاتراڤا فولاذ مقاوم للصدأ 42 مم مع ميناء أنثراسايت — نادر لباتيك فيليب.",
      storyEn: "The 6007A broke Calatrava tradition by pairing a larger 42 mm steel case with a dial referencing pilot aesthetics, available exclusively through Patek Philippe boutiques.",
      storyAr: "كسر 6007A تقليد كالاتراڤا بجمع غلاف 42 مم من الفولاذ مع ميناء مستوحى من ساعات الطيارين.",
      material: "Stainless Steel",
      dialColor: "Anthracite",
      caseSize: "42mm",
      movement: "Caliber 30-255 PS — Automatic",
      complications: "Date, Sweep Seconds",
      powerReserve: "48 hours",
      waterResistance: "30m",
      yearReleased: 2019,
      retailPrice: 32000,
      marketValue: 48000,
      rarity: "Rare",
      mainImageUrl: "/watches-collection/patek-calatrava-6007a-1681913797813_800x.webp",
      displayOrder: 4,
      isActive: true,
    },
    {
      brandId: patek,
      referenceNumber: "5719-10G-010",
      nameEn: "Patek Philippe Nautilus 5719/10G Diamond Green",
      nameAr: "باتيك فيليب نوتيلوس 5719/10G ألماس أخضر",
      slug: "patek-philippe-nautilus-5719-diamond-green",
      descriptionEn: "The most opulent Nautilus: 35.2 mm white gold set with 432 brilliant-cut diamonds, over a green sunburst dial. Every diamond hand-set in Geneva with total weight exceeding 3 carats.",
      descriptionAr: "نوتيلوس ذهب أبيض 35.2 مم مرصع بـ 432 ألماسة فوق ميناء أخضر لامع.",
      storyEn: "The 5719/10G elevates the Nautilus from icon to jewel masterpiece. Every diamond is hand-set in Geneva by Patek Philippe's in-house gem-setting atelier.",
      storyAr: "يرفع 5719/10G نوتيلوس من أيقونة إلى تحفة جوهرية. كل ألماسة تُرصّع يدويًا في جنيف.",
      material: "18K White Gold, Diamond-set bezel & lugs",
      dialColor: "Green Sunburst",
      caseSize: "35.2mm",
      movement: "Caliber 240 — Ultra-thin Automatic (3.88mm)",
      complications: "Hours, Minutes, Sweep Seconds, Date",
      powerReserve: "48 hours",
      waterResistance: "60m",
      yearReleased: 2021,
      retailPrice: 280000,
      marketValue: 420000,
      rarity: "Extremely Rare",
      mainImageUrl: "/watches-collection/patek-nautilus-green-dial-diamond-1681913804026_800x.webp",
      isFeatured: true,
      displayOrder: 5,
      isActive: true,
    },
    {
      brandId: patek,
      referenceNumber: "5726-1A-014",
      nameEn: "Patek Philippe Nautilus 5726/1A Perpetual Calendar",
      nameAr: "باتيك فيليب نوتيلوس 5726/1A تقويم دائم",
      slug: "patek-philippe-nautilus-5726-perpetual-calendar",
      descriptionEn: "A 40.5 mm stainless-steel Nautilus with one of the most coveted perpetual calendar movements. The moon-phase aperture at 3 o'clock is accurate to one day in 122 years.",
      descriptionAr: "نوتيلوس فولاذ مقاوم للصدأ 40.5 مم مع تقويم دائم كامل وطور القمر.",
      storyEn: "Patek's Nautilus Perpetual Calendar fuses the iconic octagonal bezel with perpetual calendar — day, date, month, moon phase, and leap year — accurate without correction until 2100.",
      storyAr: "يجمع نوتيلوس التقويم الدائم بين الإطار الثماني الأيقوني والتقويم الكامل الدائم.",
      material: "Stainless Steel",
      dialColor: "Silver/Blue with Moon Phase",
      caseSize: "40.5mm",
      movement: "Caliber 324 S QA LU 24H/303 — Automatic",
      complications: "Perpetual Calendar, Moon Phase, Day, Date, Month, Leap Year",
      powerReserve: "45 hours",
      waterResistance: "120m",
      yearReleased: 2014,
      retailPrice: 80000,
      marketValue: 175000,
      rarity: "Extremely Rare",
      mainImageUrl: "/watches-collection/patek-philippe-nautilus-perpetual-calendar-1681913819958_800x.webp",
      isFeatured: true,
      displayOrder: 6,
      isActive: true,
    },
    {
      brandId: patek,
      referenceNumber: "5230G-013",
      nameEn: "Patek Philippe World Time 5230G Manama Edition",
      nameAr: "باتيك فيليب ورلد تايم 5230G - طبعة المنامة",
      slug: "patek-philippe-world-time-5230g-manama",
      descriptionEn: "One of only 25 pieces in white gold, commissioned to celebrate Patek Philippe's 50th anniversary in Bahrain. The red guilloché dial references the Bahraini flag, and 'Manama' replaces Moscow on the 24-hour city ring.",
      descriptionAr: "واحدة من 25 قطعة فقط من الذهب الأبيض، احتفالاً بالذكرى الـ 50 لباتيك فيليب في البحرين.",
      storyEn: "Created in 2017–18 for Bahrain, this reference embeds geography and heritage into haute horlogerie: the crimson guilloché dial and the Manama inscription transform it into a treasured piece of regional history.",
      storyAr: "أُنشئت عام 2017-18 للبحرين. الميناء الأحمر المنقوش وكتابة 'المنامة' تحوّلانها إلى قطعة تاريخية إقليمية ثمينة.",
      material: "18K White Gold",
      dialColor: "Red Guilloché (Bahraini flag)",
      caseSize: "38.5mm",
      movement: "Caliber 240 HU — Ultra-thin Automatic (22K gold micro-rotor)",
      complications: "World Time (24 cities), Day/Night Indicator",
      powerReserve: "48 hours",
      waterResistance: "30m",
      limitedEdition: true,
      productionQuantity: 25,
      yearReleased: 2018,
      retailPrice: 65000,
      marketValue: 110000,
      rarity: "Ultra Rare — 25 pieces",
      mainImageUrl: "/watches-collection/patek-world-time-manama-1681913828669_800x.webp",
      isFeatured: true,
      displayOrder: 7,
      isActive: true,
    },
    {
      brandId: patek,
      referenceNumber: "5726A-014",
      nameEn: "Patek Philippe Nautilus Perpetual Calendar Green Dial",
      nameAr: "باتيك فيليب نوتيلوس تقويم دائم ميناء أخضر",
      slug: "patek-philippe-nautilus-perpetual-calendar-green",
      descriptionEn: "The 2021 khaki-green dial variant of the 5726 — among the most sought-after modern Patek releases, combining the sporty Nautilus case with a full perpetual calendar and the defining olive-green tone.",
      descriptionAr: "إصدار الميناء الأخضر الزيتوني لعام 2021 من 5726، من أكثر إصدارات باتيك المعاصرة طلبًا.",
      material: "Stainless Steel",
      dialColor: "Olive/Khaki Green",
      caseSize: "40.5mm",
      movement: "Caliber 324 S QA LU 24H/303 — Automatic",
      complications: "Perpetual Calendar, Moon Phase, Day, Date, Month",
      powerReserve: "45 hours",
      waterResistance: "120m",
      yearReleased: 2021,
      retailPrice: 87000,
      marketValue: 220000,
      rarity: "Extremely Rare",
      mainImageUrl: "/watches-collection/patek-perpetual-calendar-green-1681913811529_800x.webp",
      isFeatured: true,
      displayOrder: 8,
      isActive: true,
    },

    // ── RICHARD MILLE ─────────────────────────────────────────────────────
    {
      brandId: rm,
      referenceNumber: "RM 65-01",
      nameEn: "Richard Mille RM 65-01 McLaren Split-Seconds Chronograph",
      nameAr: "ريتشارد ميل RM 65-01 ماكلارين كرونوغراف الثواني المنقسمة",
      slug: "richard-mille-rm-65-01-mclaren",
      descriptionEn: "Co-developed with McLaren, the RM 65-01 packs a split-seconds chronograph into a 44.5 mm Carbon TPT® case weighing 38.3 g — among the most technically ambitious wristwatches ever made.",
      descriptionAr: "طوّرت مع ماكلارين، تضم RM 65-01 كاليبر كرونوغراف الثواني المنقسمة في غلاف Carbon TPT® 44.5 مم بوزن 38.3 جرام.",
      storyEn: "The RM 65-01 is Richard Mille's most complex automatic: split-seconds hand, column-wheel, and vertical clutch are visible through the skeletonised dial. McLaren orange accents reference the iconic Gulf racing livery.",
      storyAr: "تُعدّ RM 65-01 أكثر محركات ريتشارد ميل الأوتوماتيكية تعقيدًا. عقارب الثواني المنقسمة مرئية من خلال الميناء الهيكلي.",
      material: "Carbon TPT® / Titanium",
      dialColor: "Skeletonised with McLaren orange accents",
      caseSize: "44.5 x 49.94mm",
      movement: "Caliber RMAC4 — Automatic, Split-Seconds Chronograph",
      complications: "Split-Seconds Chronograph, Hours, Minutes, Seconds",
      powerReserve: "50 hours",
      waterResistance: "50m",
      limitedEdition: true,
      productionQuantity: 500,
      yearReleased: 2020,
      retailPrice: 650000,
      marketValue: 720000,
      rarity: "Very Rare — 500 pieces",
      mainImageUrl: "/watches-collection/rm26-02-1674211731885_800x.webp",
      isFeatured: true,
      displayOrder: 9,
      isActive: true,
    },
    {
      brandId: rm,
      referenceNumber: "RM 67-02",
      nameEn: "Richard Mille RM 67-02 Alexis Pinturault Extra Flat",
      nameAr: "ريتشارد ميل RM 67-02 أليكسي بانتوروه - رفيع استثنائي",
      slug: "richard-mille-rm-67-02-italia",
      descriptionEn: "Dedicated to Olympic alpine champion Alexis Pinturault, this RM 67-02 in Quartz TPT® Italian flag colours weighs just 32 g and at 7.75 mm is Richard Mille's thinnest automatic — worn on slopes at 140 km/h.",
      descriptionAr: "مخصص لبطل التزلج الأولمبي أليكسي بانتوروه، هذا RM 67-02 من Quartz TPT® يزن 32 جرام فقط بسمك 7.75 مم.",
      storyEn: "Pinturault wore prototypes during World Cup training runs, proving it could withstand extreme G-forces. The Italian flag Quartz TPT® is produced by layering hundreds of silica fibre sheets at different orientations.",
      storyAr: "ارتدى بانتوروه نماذج أولية خلال تدريبات كأس العالم لإثبات قدرتها على تحمّل قوى الجاذبية الشديدة.",
      material: "Quartz TPT® — Italian flag colours",
      dialColor: "Skeletonised — red/white/green accents",
      caseSize: "38.7 x 47.52mm",
      movement: "Caliber CRMA7 — Automatic Extra Flat (7.75mm total)",
      complications: "Hours, Minutes, Seconds",
      powerReserve: "50 hours",
      waterResistance: "50m",
      limitedEdition: true,
      productionQuantity: 150,
      yearReleased: 2018,
      retailPrice: 100000,
      marketValue: 115000,
      rarity: "Very Rare — 150 pieces",
      mainImageUrl: "/watches-collection/rm67-02-alexis-pinturault-1681913841692_800x.webp",
      isFeatured: true,
      displayOrder: 10,
      isActive: true,
    },
    {
      brandId: rm,
      referenceNumber: "RM 68-01",
      nameEn: "Richard Mille RM 68-01 Tourbillon Cyril Kongo",
      nameAr: "ريتشارد ميل RM 68-01 توربيون سيريل كونغو",
      slug: "richard-mille-rm-68-01-cyril-kongo",
      descriptionEn: "A collaboration with French graffiti legend Cyril Kongo. Only 30 pieces, every one unique: Kongo hand-painted each movement bridge with a custom micro-airbrush developed over a year, making each watch a singular artwork.",
      descriptionAr: "تعاون مع الفنان الأسطوري سيريل كونغو. 30 قطعة فقط، كل واحدة فريدة: رسم كونغو يدويًا كل قطعة.",
      storyEn: "Developing the airbrush technique took over a year. The result is a flying tourbillon where art and engineering are literally inseparable — each one a unique masterpiece.",
      storyAr: "استغرق تطوير أسلوب الرسم أكثر من عام. النتيجة توربيون طائر لا يمكن فيه الفصل بين الفن والهندسة.",
      material: "Carbon TPT® / TZP Black Ceramic",
      dialColor: "Multi-colour graffiti on sapphire",
      caseSize: "50.2 x 42.7mm",
      movement: "Caliber RM 68-01 — Manual-winding Flying Tourbillon",
      complications: "Flying Tourbillon, Hours, Minutes",
      powerReserve: "42 hours",
      waterResistance: "50m",
      limitedEdition: true,
      productionQuantity: 30,
      yearReleased: 2016,
      retailPrice: 685000,
      marketValue: 2100000,
      rarity: "Ultra Rare — 30 unique pieces",
      mainImageUrl: "/watches-collection/rm-cyril-kongo-1674216610713_800x.webp",
      isFeatured: true,
      displayOrder: 11,
      isActive: true,
    },

    // ── AUDEMARS PIGUET ───────────────────────────────────────────────────
    {
      brandId: ap,
      referenceNumber: "26574ST",
      nameEn: "Audemars Piguet Royal Oak Perpetual Calendar 26574ST",
      nameAr: "أوديمار بيغيه رويال أوك تقويم دائم 26574ST",
      slug: "audemars-piguet-royal-oak-perpetual-calendar",
      descriptionEn: "A 41 mm stainless-steel Royal Oak with ultra-thin Caliber 5134, complete perpetual calendar and moon phase — all in 4.31 mm of movement thickness.",
      descriptionAr: "رويال أوك فولاذ 41 مم مع الكاليبر الرفيع 5134 والتقويم الدائم الكامل في 4.31 مم من سماكة المحرك.",
      storyEn: "The Royal Oak Perpetual Calendar dates to 1984 — one of the oldest perpetual calendar complications in steel. This 2020 iteration updates the case while retaining the timeless Genta silhouette.",
      storyAr: "يعود تاريخ رويال أوك التقويم الدائم إلى 1984. هذا الإصدار 2020 يحدّث الهيكل مع الحفاظ على صورة جينتا.",
      material: "Stainless Steel",
      dialColor: "Blue Grande Tapisserie",
      caseSize: "41mm",
      movement: "Caliber 5134 — Ultra-thin Automatic (4.31mm)",
      complications: "Perpetual Calendar, Moon Phase, Day, Date, Month, Leap Year",
      powerReserve: "40 hours",
      waterResistance: "50m",
      yearReleased: 2020,
      retailPrice: 85000,
      marketValue: 120000,
      rarity: "Very Rare",
      mainImageUrl: "/watches-collection/royal-oak-white-1674201595442_800x.webp",
      isFeatured: true,
      displayOrder: 12,
      isActive: true,
    },
    {
      brandId: ap,
      referenceNumber: "15202BC-ZZ-1240BC-01",
      nameEn: "Audemars Piguet Royal Oak Jumbo 15202BC White Gold",
      nameAr: "أوديمار بيغيه رويال أوك جامبو 15202BC ذهب أبيض",
      slug: "audemars-piguet-royal-oak-jumbo-15202bc",
      descriptionEn: "The 50th-anniversary Jumbo in 18K white gold: 39 mm with the ultra-thin Caliber 2121 (3.05 mm), unchanged in principle since 1972. Only 500 pieces — instantly the most collectible modern Royal Oak.",
      descriptionAr: "جامبو الذكرى الـ 50 من الذهب الأبيض: 39 مم مع الكاليبر 2121 (3.05 مم). 500 قطعة فقط.",
      storyEn: "Ref. 15202 is the faithful heir of Genta's original A-series. The 15202BC — unveiled at Watches & Wonders 2022 — was back-ordered for years. It is the purest expression of Royal Oak DNA.",
      storyAr: "المرجع 15202 هو الوريث الأمين لتصميم جينتا الأصلي. كُشف عنه في الذكرى الـ 50 وكانت الطلبات المسبقة تمتد لسنوات.",
      material: "18K White Gold",
      dialColor: "Silver Petite Tapisserie",
      caseSize: "39mm",
      movement: "Caliber 2121 — Ultra-thin Automatic (3.05mm)",
      complications: "Hours, Minutes, Date",
      powerReserve: "40 hours",
      waterResistance: "50m",
      limitedEdition: true,
      productionQuantity: 500,
      yearReleased: 2022,
      retailPrice: 75000,
      marketValue: 130000,
      rarity: "Extremely Rare — 500 pieces",
      mainImageUrl: "/watches-collection/royal-oak-jumbo-15202bc-1681913914790_800x.webp",
      isFeatured: true,
      displayOrder: 13,
      isActive: true,
    },
    {
      brandId: ap,
      referenceNumber: "26510OR-OO-1220OR-01",
      nameEn: "Audemars Piguet Royal Oak Extra-Thin Tourbillon Salmon",
      nameAr: "أوديمار بيغيه رويال أوك رفيع توربيون ميناء سالمون",
      slug: "audemars-piguet-royal-oak-tourbillon-salmon",
      descriptionEn: "18K rose-gold Royal Oak Extra-Thin Tourbillon with salmon Grande Tapisserie dial and flying tourbillon at 6 o'clock. At 9.5 mm total thickness it is extraordinary for a tourbillon.",
      descriptionAr: "رويال أوك رفيع استثنائي من الذهب الوردي مع ميناء سالمون وتوربيون طائر. سمك إجمالي 9.5 مم.",
      storyEn: "The Extra-Thin Tourbillon continues AP's pursuit of combining iconic design with the most exacting complications. The warm salmon dial makes this one of the most photographed Royal Oaks of the decade.",
      storyAr: "يواصل التوربيون الرفيع مسيرة AP في الجمع بين التصميم الأيقوني والتعقيدات الأدق.",
      material: "18K Rose Gold",
      dialColor: "Salmon Grande Tapisserie",
      caseSize: "41mm",
      movement: "Caliber 2924 — Manual-winding Flying Tourbillon (9.5mm total)",
      complications: "Flying Tourbillon, Hours, Minutes",
      powerReserve: "70 hours",
      waterResistance: "20m",
      yearReleased: 2021,
      retailPrice: 245000,
      marketValue: 280000,
      rarity: "Extremely Rare",
      mainImageUrl: "/watches-collection/royal-oak-salmon-dial-tourbillon-1674208549211_800x.webp",
      isFeatured: true,
      displayOrder: 14,
      isActive: true,
    },
    {
      brandId: ap,
      referenceNumber: "26240CE-OO-1225CE-01",
      nameEn: "Audemars Piguet Royal Oak Chronograph Ice Blue",
      nameAr: "أوديمار بيغيه رويال أوك كرونوغراف - الميناء الأزرق الجليدي",
      slug: "audemars-piguet-royal-oak-chronograph-ice-blue",
      descriptionEn: "41 mm cermet Royal Oak Chronograph with the breathtaking Ice Blue dial — available only in ceramic composite and considered one of the most beautiful dials AP has ever produced.",
      descriptionAr: "رويال أوك كرونوغراف 41 مم من السيراميك مع ميناء 'أزرق جليدي' مذهل.",
      material: "Ceramic (Cermet)",
      dialColor: "Ice Blue Grande Tapisserie",
      caseSize: "41mm",
      movement: "Caliber 4405 — Automatic Chronograph",
      complications: "Chronograph, Hours, Minutes, Seconds, Date",
      powerReserve: "70 hours",
      waterResistance: "50m",
      yearReleased: 2021,
      retailPrice: 38000,
      marketValue: 65000,
      rarity: "Very Rare",
      mainImageUrl: "/watches-collection/royal-oak-chronograph-ice-blue-dial-1674203067787_800x.webp",
      displayOrder: 15,
      isActive: true,
    },

    // ── ROLEX ─────────────────────────────────────────────────────────────
    {
      brandId: rolex,
      referenceNumber: "6265/8",
      nameEn: "Rolex Daytona 6265/8 'Paul Newman' 18K Yellow Gold",
      nameAr: "رولكس دايتونا 6265/8 'بول نيومان' ذهب أصفر 18 قيراط",
      slug: "rolex-daytona-paul-newman-6265-8",
      descriptionEn: "A 1987 vintage 18K yellow gold Daytona bearing the legendary 'exotic' Paul Newman dial — stepped sub-registers, Art Deco numerals, and contrasting colour rings define the most coveted vintage Rolex.",
      descriptionAr: "دايتونا عتيقة 1987 من الذهب الأصفر 18 قيراطًا تحمل الميناء الأسطوري المعروف بـ 'بول نيومان'.",
      storyEn: "Paul Newman's personal 6239 sold at Phillips for $17.75M in 2017. The gold 6265 with exotic dial represents the zenith of Daytona collecting — precious metal meeting the world's most recognised chronograph dial.",
      storyAr: "بيعت ساعة بول نيومان الشخصية 6239 بـ 17.75 مليون دولار. نسخة الذهب 6265 تمثل ذروة جمع الدايتونا.",
      material: "18K Yellow Gold",
      dialColor: "Paul Newman 'Exotic' — Black, Gold sub-registers",
      caseSize: "37mm",
      movement: "Caliber 727 (Valjoux-based) — Manual-winding",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "48 hours",
      yearReleased: 1987,
      retailPrice: 15000,
      marketValue: 200000,
      rarity: "Extremely Rare — Vintage",
      mainImageUrl: "/watches-collection/rolex-daytona-6265-1681913867168_800x.webp",
      isFeatured: true,
      displayOrder: 16,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "6239-PN",
      nameEn: "Rolex Daytona 6239 'Paul Newman' Exotic Dial",
      nameAr: "رولكس دايتونا 6239 'بول نيومان' ميناء إكزوتيك",
      slug: "rolex-daytona-6239-paul-newman",
      descriptionEn: "The original Paul Newman Daytona — Reference 6239 (1963–1969). Stainless steel with Valjoux 72B movement and the iconic exotic dial that inspired a $17.75 million auction record.",
      descriptionAr: "دايتونا بول نيومان الأصلية — المرجع 6239 (1963-1969). فولاذ مع محرك Valjoux 72B والميناء الإكزوتيك الأسطوري.",
      storyEn: "Newman wore his 6239 — engraved 'Drive Carefully Me' by Joanne Woodward — until his death in 2008. His personal watch sold for $17.75M at Phillips 2017. Any authentic example commands $200,000–$500,000.",
      storyAr: "ارتدى نيومان ساعته حتى وفاته عام 2008. بيعت ساعته الشخصية بـ 17.75 مليون دولار.",
      material: "Stainless Steel",
      dialColor: "Paul Newman 'Exotic' — White, Black sub-registers",
      caseSize: "36mm",
      movement: "Caliber Valjoux 72B / 722 — Manual-winding, 17 jewels",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "45 hours",
      yearReleased: 1965,
      retailPrice: 250,
      marketValue: 350000,
      rarity: "Extremely Rare — Vintage Icon",
      mainImageUrl: "/watches-collection/rolex-daytona-6239-paul-newman-1681913854878_800x.webp",
      isFeatured: true,
      displayOrder: 17,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "6263-ADG",
      nameEn: "Rolex Daytona 6263 'Quraysh' by Artisans de Genève",
      nameAr: "رولكس دايتونا 6263 'قريش' — آرتيزانس دو جينيف",
      slug: "rolex-daytona-6263-quraysh-artisans-de-geneve",
      descriptionEn: "A vintage Ref. 6263 Daytona comprehensively transformed by Artisans de Genève. Named for the noble Arabian tribe, every surface is hand-finished to bespoke specification with unique Arabic calligraphy and custom engravings.",
      descriptionAr: "دايتونا 6263 عتيقة تحوّلت بالكامل على يد آرتيزانس دو جينيف. مسمّاة باسم القبيلة العربية النبيلة 'قريش'.",
      storyEn: "Artisans de Genève answers the question: what if you combined a vintage Rolex with Swiss Manufacture hand-finishing standards? The Quraysh edition celebrates Arab culture through enamel dials and hand-engraved movement bridges.",
      storyAr: "آرتيزانس دو جينيف يجيب: ماذا لو جمعنا رولكس عتيقة بمعايير التشطيب اليدوي السويسري؟ 'قريش' يحتفل بالثقافة العربية.",
      material: "Stainless Steel (custom finished)",
      dialColor: "Custom Enamel with Arabic calligraphy",
      caseSize: "37mm",
      movement: "Caliber Valjoux 727 — Manual-winding (hand-finished)",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "48 hours",
      limitedEdition: true,
      productionQuantity: 1,
      yearReleased: 2020,
      retailPrice: 75000,
      marketValue: 180000,
      rarity: "Ultra Rare — Unique Commission",
      mainImageUrl: "/watches-collection/rolex-daytona-6263-quraysh-1674202164605_800x.webp",
      isFeatured: true,
      displayOrder: 18,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "6264-SS",
      nameEn: "Rolex Daytona 6264 Vintage",
      nameAr: "رولكس دايتونا 6264 عتيق",
      slug: "rolex-daytona-6264-vintage",
      descriptionEn: "Reference 6264 was produced for just one year (1969–70), among the shortest-run Daytonas ever — a transitional reference bridging the 6239 era and the long-running 6263/6265 generation.",
      descriptionAr: "أُنتج المرجع 6264 لسنة واحدة فقط (1969-70)، من أقصر إنتاجًا للدايتونا.",
      material: "Stainless Steel",
      dialColor: "White with black sub-registers",
      caseSize: "37mm",
      movement: "Caliber Valjoux 727 — Manual-winding",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "48 hours",
      yearReleased: 1969,
      retailPrice: 500,
      marketValue: 60000,
      rarity: "Extremely Rare — One-year production",
      mainImageUrl: "/watches-collection/rolex-daytona-6264-1681913860634_800x.webp",
      displayOrder: 19,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "6265-JPS",
      nameEn: "Rolex Daytona 6265 'John Player Special'",
      nameAr: "رولكس دايتونا 6265 'جون بلاير سبيشال'",
      slug: "rolex-daytona-6265-john-player-special",
      descriptionEn: "A 6265 in yellow gold with black dial and golden sub-registers — nicknamed 'John Player Special' after the legendary black-and-gold Lotus F1 racing livery. Among the most sought-after Daytona colour combinations.",
      descriptionAr: "دايتونا 6265 من الذهب الأصفر مع ميناء أسود وساعات فرعية ذهبية، ملقبة بـ 'جون بلاير سبيشال' إشارة إلى سيارات لوتس الفورمولا 1.",
      material: "18K Yellow Gold",
      dialColor: "Black dial, Gold sub-registers (JPS)",
      caseSize: "37mm",
      movement: "Caliber Valjoux 727 — Manual-winding",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "48 hours",
      yearReleased: 1977,
      retailPrice: 8000,
      marketValue: 120000,
      rarity: "Extremely Rare — Vintage",
      mainImageUrl: "/watches-collection/rolex-daytona-john-player-special-1681913884253_800x.webp",
      displayOrder: 20,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "6265-AET",
      nameEn: "Rolex Daytona by AET Remould — Custom Edition",
      nameAr: "رولكس دايتونا — إصدار مخصص من آي إي تي ريمولد",
      slug: "rolex-daytona-aet-remould-custom",
      descriptionEn: "A Rolex Daytona 6265 transformed by Parisian atelier AET Remould — known for converting vintage sports Rolex into bold artistic statements with hand-applied patina, custom engravings, and bespoke dials.",
      descriptionAr: "دايتونا رولكس 6265 مخصصة من أتيليه AET Remould الباريسي. كل قطعة بصمة فنية جريئة لا تشبه الأخرى.",
      storyEn: "AET Remould approaches each commission like a couturier: they disassemble the Daytona, apply bespoke finishing to every component, and reassemble with custom dials and engravings. No two pieces are alike.",
      storyAr: "يتعامل AET Remould مع كل طلب كالمصمم مع الثوب. يفكّك الدايتونا ويطبق تشطيبًا مخصصًا على كل مكوّن.",
      material: "Stainless Steel (custom patina & engravings)",
      dialColor: "Custom bespoke",
      caseSize: "37mm",
      movement: "Caliber Valjoux 727 — Manual-winding (hand-finished)",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "48 hours",
      limitedEdition: true,
      productionQuantity: 1,
      yearReleased: 2019,
      retailPrice: 45000,
      marketValue: 95000,
      rarity: "Ultra Rare — Bespoke",
      mainImageUrl: "/watches-collection/rolex-daytona-aet-remould-1681913876180_800x.webp",
      displayOrder: 21,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "116519LN",
      nameEn: "Rolex Cosmograph Daytona 116519LN White Gold",
      nameAr: "رولكس كوزموغراف دايتونا 116519LN ذهب أبيض",
      slug: "rolex-daytona-white-gold-116519ln",
      descriptionEn: "40 mm 18K white gold Daytona with black ceramic bezel and black dial. Caliber 4130 — Rolex's finest in-house movement — delivers 72 hours power reserve and COSC certification.",
      descriptionAr: "دايتونا 40 مم من الذهب الأبيض 18 قيراطًا مع حافة سيراميك سوداء. الكاليبر 4130 معتمد COSC.",
      material: "18K White Gold, Black Ceramic bezel",
      dialColor: "Black Chronograph",
      caseSize: "40mm",
      movement: "Caliber 4130 — Automatic, COSC certified",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "72 hours",
      waterResistance: "100m",
      yearReleased: 2016,
      retailPrice: 39350,
      marketValue: 55000,
      rarity: "Very Rare",
      mainImageUrl: "/watches-collection/rolex-daytona-white-gold-1681913899487_800x.webp",
      displayOrder: 22,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "126710BLRO",
      nameEn: "Rolex GMT-Master II 'Pepsi' 126710BLRO",
      nameAr: "رولكس جي إم تي ماستر II 'بيبسي' 126710BLRO",
      slug: "rolex-gmt-master-ii-pepsi-126710blro",
      descriptionEn: "The iconic red-and-blue 'Pepsi' Cerachrom bezel returns on Oystersteel — the most requested Rolex in the world. Caliber 3285 delivers 70 hours power reserve and triple-timezone tracking.",
      descriptionAr: "حافة 'بيبسي' الأسطورية على فولاذ أويستر — الرولكس الأكثر طلبًا في العالم.",
      material: "Oystersteel",
      dialColor: "Black with Red/Blue 'Pepsi' Cerachrom bezel",
      caseSize: "40mm",
      movement: "Caliber 3285 — Automatic",
      complications: "GMT (3rd time zone), Date",
      powerReserve: "70 hours",
      waterResistance: "100m",
      yearReleased: 2018,
      retailPrice: 10700,
      marketValue: 17000,
      rarity: "Very Rare — High Demand",
      mainImageUrl: "/watches-collection/rolex-pepsi-1674209935187_800x.webp",
      displayOrder: 23,
      isActive: true,
    },
    {
      brandId: rolex,
      referenceNumber: "126719BLRO",
      nameEn: "Rolex GMT-Master II Pepsi White Gold Meteorite Dial",
      nameAr: "رولكس جي إم تي ماستر II بيبسي ذهب أبيض ميناء نيزكي",
      slug: "rolex-gmt-master-ii-pepsi-meteorite-white-gold",
      descriptionEn: "The pinnacle of the Pepsi GMT: 18K white gold with a Gibeon meteorite dial — each unique because no two slices of meteorite are identical. The bi-colour bezel and otherworldly dial make this the ultimate GMT.",
      descriptionAr: "قمة سلسلة GMT بيبسي: ذهب أبيض 18 قيراطًا مع ميناء نيزكي فريد من نوعه.",
      material: "18K White Gold",
      dialColor: "Gibeon Meteorite with Red/Blue 'Pepsi' Cerachrom bezel",
      caseSize: "40mm",
      movement: "Caliber 3285 — Automatic",
      complications: "GMT (3rd time zone), Date",
      powerReserve: "70 hours",
      waterResistance: "100m",
      yearReleased: 2023,
      retailPrice: 47350,
      marketValue: 60000,
      rarity: "Extremely Rare",
      mainImageUrl: "/watches-collection/rolex-pepsi-meteorite-1681913907088_800x.webp",
      isFeatured: true,
      displayOrder: 24,
      isActive: true,
    },

    // ── TUDOR ─────────────────────────────────────────────────────────────
    {
      brandId: tudor,
      referenceNumber: "79360N",
      nameEn: "Tudor Black Bay Chronograph 'Pink Dial' Inter Miami Edition",
      nameAr: "تيودور بلاك باي كرونوغراف 'القرص الوردي' — إصدار إنتر ميامي",
      slug: "tudor-black-bay-chronograph-pink-dial",
      descriptionEn: "From Tudor's partnership with Inter Miami CF, the Black Bay Chronograph in Inter Miami's signature pink. MT5813 — co-developed with Breitling — meets METAS Master Chronometer standards.",
      descriptionAr: "من شراكة تيودور مع إنتر ميامي، الكرونوغراف بوردي النادي المميز. محرك MT5813 معتمد METAS.",
      storyEn: "When Lionel Messi joined Inter Miami in 2023, Tudor released this limited pink-dial variant as official club timekeeper. It sold out within hours, immediately commanding a secondary-market premium.",
      storyAr: "عندما انضم ميسي لإنتر ميامي عام 2023، أصدرت تيودور هذا الإصدار الوردي المحدود الذي نفد في ساعات.",
      material: "Stainless Steel",
      dialColor: "Inter Miami Pink",
      caseSize: "41mm",
      movement: "Caliber MT5813 — Automatic (co-developed with Breitling), METAS certified",
      complications: "Chronograph, Date",
      powerReserve: "70 hours",
      waterResistance: "200m",
      limitedEdition: true,
      yearReleased: 2024,
      retailPrice: 5650,
      marketValue: 7500,
      rarity: "Limited Edition",
      displayOrder: 25,
      isActive: true,
    },

    // ── BREITLING ─────────────────────────────────────────────────────────
    {
      brandId: breit,
      referenceNumber: "V17310AT",
      nameEn: "Breitling Avenger Blackbird DLC Titanium",
      nameAr: "بريتلينغ أفينجر بلاك بيرد تيتانيوم DLC",
      slug: "breitling-avenger-blackbird",
      descriptionEn: "44 mm DLC-coated titanium pilot's watch with COSC-certified Caliber B17. 300 m water resistance and a slide-rule bezel make it a true professional instrument.",
      descriptionAr: "ساعة طيار تيتانيوم 44 مم مع طلاء DLC وكاليبر B17 معتمد COSC. مقاومة ماء 300 متر.",
      storyEn: "Inspired by the Lockheed SR-71 Blackbird, this Breitling takes its all-black DNA seriously: titanium case, DLC coating, black dial — every element engineered for performance.",
      storyAr: "مستوحى من SR-71 Blackbird الأسطورية، تأخذ هذه بريتلينغ حمضها الأسود بجدية.",
      material: "DLC-coated Titanium",
      dialColor: "Black",
      caseSize: "44mm",
      movement: "Caliber B17 — Automatic, COSC certified",
      complications: "Date, Slide-rule Bezel",
      powerReserve: "42 hours",
      waterResistance: "300m",
      yearReleased: 2015,
      retailPrice: 5100,
      marketValue: 5200,
      rarity: "Available",
      displayOrder: 26,
      isActive: true,
    },

    // ── H. MOSER & CIE ────────────────────────────────────────────────────
    {
      brandId: moser,
      referenceNumber: "1801-0401",
      nameEn: "H. Moser & Cie Endeavour Perpetual Moon",
      nameAr: "إتش موزر وشركاه إندياڤور طور القمر الدائم",
      slug: "h-moser-endeavour-perpetual-moon",
      descriptionEn: "H. Moser's most romantic complication: the legendary 'Funky Blue' fumé dial with a moon-phase display accurate to one day in 1,027 years. The HMC 801 is entirely developed and manufactured in Schaffhausen.",
      descriptionAr: "أكثر تعقيدات موزر رومانسية: الميناء الأسطوري 'فانكي بلو' مع طور القمر الدقيق لغاية يوم كل 1,027 عامًا.",
      storyEn: "H. Moser's moon-phase is calibrated to one day every 1,027 years — approximately ten times more precise than most competitors. The fumé dials, produced in-house, vary in colour from piece to piece, ensuring every Moser is unique.",
      storyAr: "معيار طور القمر في موزر دقيق لغاية يوم واحد كل 1,027 عامًا. تختلف ألوان الميناء من قطعة لأخرى.",
      material: "18K Rose Gold",
      dialColor: "Funky Blue Fumé",
      caseSize: "40.8mm",
      movement: "Caliber HMC 801 — Manual-winding, in-house Schaffhausen",
      complications: "Perpetual Moon Phase, Hours, Minutes",
      powerReserve: "168 hours (7 days)",
      waterResistance: "30m",
      yearReleased: 2018,
      retailPrice: 38000,
      marketValue: 45000,
      rarity: "Very Rare",
      mainImageUrl: "/watches-collection/h-moser-1674217667237_800x.webp",
      displayOrder: 27,
      isActive: true,
    },

    // ── ARTISANS DE GENÈVE custom (listed under Rolex brand) ──────────────
    {
      brandId: rolex,
      referenceNumber: "ADG-MONTOYA-6263",
      nameEn: "Artisans de Genève 'La Montoya' — Custom Daytona 6263",
      nameAr: "آرتيزانس دو جينيف 'لا مونتويا' — دايتونا 6263 مخصصة",
      slug: "artisans-de-geneve-la-montoya",
      descriptionEn: "A one-of-a-kind vintage Rolex Daytona 6263 transformed by Geneva's foremost bespoke atelier. 'La Montoya' bears hand-engraved bridges, a Marlboro red lacquer dial, and over 200 hours of individual hand-finishing — a tribute to Juan Pablo Montoya and motor racing heritage.",
      descriptionAr: "دايتونا رولكس 6263 عتيقة فريدة حوّلتها آرتيزانس دو جينيف. 'لا مونتويا' تحمل جسورًا منقوشة يدويًا وميناء أحمر لاكيه مخصصًا.",
      storyEn: "Artisans de Genève ask: what if you combined a vintage Rolex with Swiss Manufacture hand-finishing? La Montoya — named for the Colombian F1 champion — is the answer: 200+ hours of bespoke work on a 6263 base, including hand-painted sub-dials and acid-etched movement bridges.",
      storyAr: "آرتيزانس دو جينيف تسأل: ماذا لو جمعنا رولكس عتيقة بمعايير التشطيب السويسري؟ 'لا مونتويا' هي الإجابة.",
      material: "Stainless Steel (hand-finished, custom patina)",
      dialColor: "Custom Marlboro Red Lacquer",
      caseSize: "37mm",
      movement: "Caliber Valjoux 727 — Manual-winding (extensively hand-finished)",
      complications: "Chronograph, Tachymetre Bezel",
      powerReserve: "48 hours",
      limitedEdition: true,
      productionQuantity: 1,
      yearReleased: 2021,
      retailPrice: 120000,
      marketValue: 250000,
      rarity: "Ultra Rare — Unique Commission",
      mainImageUrl: "/watches-collection/artisans-de-geneve-la-montoya-1681913755711_800x.webp",
      isFeatured: true,
      displayOrder: 28,
      isActive: true,
    },
  ];

  for (const w of watches) {
    await upsertWatch(db, w);
  }

  console.log(`[Migration] enrichWatchCollection: inserted/updated ${watches.length} watches.`);
}
